#include<iostream>
using namespace std;
int main()
{
    char ch;
    cout<<"Enter any letter :";
    cin>>ch;

    ch=tolower(ch);
switch(ch) {
    case 'a':
    cout<<"vowel";
    break;
   case 'e':
    cout<<"vowel";
    break;
    case 'i':
    cout<<"vowel";
    break;
    case 'o':
    cout<<"vowel";
    break;
    case 'u':
    cout<<"vowel";
    break;

default:
cout<<"consonent";


}
}

  //int color=4;
 // switch (color){
   // case 1:
   // break;
   // cout<<"Merun:Law,English";
   // case 2:
   // break;
   // cout<<"Yellow:EEE,COE";
   // case 3:
   // break;
   // cout<<"Green:BBA";
   // break;
   // case 4:
   // cout<<"Blue:CSE,CS";
    //break;
   // default:
   // cout<<"None";
  

